### ISSUE TITLE
Suggested option: --env-file

### ISSUE THREAD

**Issue by liger1978** [jordansissel/pleaserun#107]
When I create systemd unit files, I sometimes use the `EnvironmentFile` directive so that environment config variables can be stored separately from the unit file.  Similarly in sys-v init scripts one can "dot source" a file to include its environment.   How about a `--env-file` option for pleaserun that adds the relevant line to the init script/config?

**Comment by josegonzalez** [comment]
Should the file exist verbatim? What happens when a user "installs" the process? Should we move that file to `/etc/default` somewhere and include it from there, or just leave it "bare". Are there process managers that don't support sourcing a file?
