### ISSUE TITLE
only print out the existance of a log file if errors occur

### ISSUE THREAD

**Issue by jsvd** [jordansissel/pleaserun#108]
Right now pleaserun will output something like:

```
Sending all logs to /tmp/tmp.lbr2SaG6st
Successfully created system startup script ..
```

but if the pleasrun action succeeds then the file will not exist.

I think pleaserun should only announce the existence of this log file if it detects errors occurred, otherwise it can be silent.

**Comment by jordansissel** [comment]
ehhh. I'm on the fence about this one.

The `Sending all logs ...` occurs only if STDERR is attached to a tty: https://github.com/jordansissel/pleaserun/blob/master/lib/pleaserun/cli.rb#L199

This is to hint to humans invoking this via terminal that the logs are in a specific location. If this is not desirable, we could add a flag or for a workaround you could direct stderr to /dev/null (which will fail the `tty?` check)

As for the `Successfully created` log message, I do not see this in pleaserun. I do see it in Logstash's `bin/system-install` though.

**Comment by jordansissel** [comment]
Tell you what. I'll comment out the 'Sending all logs ...' line and see what happens. <3

**Comment by jordansissel** [comment]
Done! <3
