### ISSUE TITLE
Upstart 0.6.5 environment variable support

### ISSUE THREAD

**Issue by gunzy83** [jordansissel/pleaserun#115]
Please forgive my ignorance but I saw that in #111 support for sourcing a default and sysconfig file was added to the default Upstart template and was wondering if there was a reason it was omitted on the 0.6.5 version of it?

I have patched it [here](https://github.com/gunzy83/pleaserun/commit/f28c512e352cf95954ce15a89ae4b2e0b1c5d276) and it seems to work as intended. I can issue a PR if it is ok?

**Comment by jordansissel** [comment]
probably omitted on accident. I'd love a patch :)

**Comment by gunzy83** [comment]
Done :)
