### ISSUE TITLE
Feature request: an option flag for outputting the version of pleaserun

### ISSUE THREAD

**Issue by elasticdog** [jordansissel/pleaserun#125]
Since it's pretty easy to have multiple versions of a gem installed on a machine and it's not always immediately obvious which binary is being called, so it would be useful if pleaserun had an option flag to output the current version that is being used. I realize that the standard `--version` is already used for other purposes, but it could even be a part of the `--help` output.

**Comment by jordansissel** [comment]
pleaserun v0.0.29 published with this:

```
% pleaserun --version
0.0.29
% pleaserun --help |& head -1
Welcome to pleaserun version 0.0.29!
```
