### ISSUE TITLE
--no-install-actions does not work

### ISSUE THREAD

**Issue by spuder** [jordansissel/pleaserun#147]
I am attempting to use pleaserun + fpm to generate init scripts for a go binary. 

I may be doing it wrong, but it appears that `--no-install-actions` flag is not implemented since I get the exact same results regardless if it is defined or not. 

## Expected behavior

I expect running `pleaserun --platform systemd --install-prefix ./buildroot` to _not_ generate `install-actions.sh`

## Actual result

All of the following commands generate a install_actions.sh file which I need to manually clean up
```
pleaserun --platform systemd --no-install-actions --install-prefix ./buildroot
ls buildroot | grep install_actions.sh
install_actions.sh   # <--- I expect this file to be absent, which it is not
```

```
pleaserun --platform systemd -install-actions --install-prefix ./buildroot
ls buildroot | grep install_actions.sh
install_actions.sh # <--- I expect this file to be present, which it is 
```

## Workaround

Manually remove any install_actions.sh scripts before building with fpm

```
please run \
--name foobar \
--platform systemd \ 
--no-install-actions \
--install-prefix ./buildroot
/usr/local/bin/foobar

rm buildroot/install_actions.sh # <--- This is the work around

fpm \
--input-type dir \
--output-type deb \
--chdir ./buildroot \
--package output/ \
. 
```

Am I misunderstanding `--no-install-actions`? Or is it broken/absent? 
I looked at the source, and there is only 1 line of code where `install-actions` is referenced https://github.com/jordansissel/pleaserun/search?q=install-actions

**Comment by jordansissel** [comment]
Thanks for the detailed report!

Given your examples, I agree this seems to be a bug (and something that
maybe never got implemented?)

**Comment by spuder** [comment]
Indeed it appears to never be implemented.

I'll keep looking but I suspect there needs to be a conditional added here:

https://github.com/jordansissel/pleaserun/blob/972cff10fab32703303fd26c4c97d21ce2a1eedf/lib/pleaserun/platform/systemd.rb#L33

**Comment by jordansissel** [comment]
https://github.com/jordansissel/pleaserun/pull/148 should fix

**Comment by jordansissel** [comment]
#148 merged. pleaserun v0.0.32 published. :)

**Comment by spuder** [comment]
Thank you. I see `pleaserun` [v0.0.32](https://rubygems.org/gems/pleaserun) is live on rubygems.org.

Does something need to happen to update the bundled version of `pleaserun` inside of the `fpm` gem? 

Installing the latest version of fpm in a docker container, still returns the old version of pleaserun. 

```
FROM alpine
RUN apk add ruby ruby-dev make git gcc libc-dev ruby-etc tar --no-cache && \
    gem install fpm --no-document
```
```
docker run -it -v $(pwd):/data fpm:0.0.3 pleaserun --version
0.0.31
```
