### ISSUE TITLE
[FEATURE] Add an option for where to write the init scripts

### ISSUE THREAD

**Issue by lookfirst** [jordansissel/pleaserun#43]
By default, pleaserun seems to output to a temp file. I'd like to be able to specify a directory for where it should write the files.

**Comment by jordansissel** [comment]
@spuder I am ... almost liking that proposal, though this would be the same as `-p sysv -d /tmp/sysv` repeated for each platform type.

**Comment by jordansissel** [comment]
pleaserun 0.0.9 published with an `--install-prefix` flag:

```
% bin/pleaserun --install --install-prefix /tmp/fancy -p sysv -v lsb-3.1 --name apache /usr/bin/httpd -D
Writing file {:destination=>"/tmp/fancy/etc/init.d/apache"}
Writing file {:destination=>"/tmp/fancy/etc/default/apache"}
```

**Comment by lookfirst** [comment]
:+1:
