### ISSUE TITLE
Does not detect OpenSUSE 13.1

### ISSUE THREAD

**Issue by evaryont** [jordansissel/pleaserun#51]
Running `pleaserun /usr/bin/screen` (to test & play with pleaserun) nets me:

```
/home/colin/dotfiles/share/rbenv/versions/2.1.2/lib64/ruby/gems/2.1.0/gems/pleaserun-0.0.7/lib/pleaserun/detector.rb:44:in `detect': PleaseRun::Detector::UnknownSystem (PleaseRun::Detector::UnknownSystem)
        from /home/colin/dotfiles/share/rbenv/versions/2.1.2/lib64/ruby/gems/2.1.0/gems/pleaserun-0.0.7/lib/pleaserun/cli.rb:139:in `setup_defaults'
        from /home/colin/dotfiles/share/rbenv/versions/2.1.2/lib64/ruby/gems/2.1.0/gems/pleaserun-0.0.7/lib/pleaserun/cli.rb:106:in `execute'
        from /home/colin/dotfiles/share/rbenv/versions/2.1.2/lib64/ruby/gems/2.1.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
        from /home/colin/dotfiles/share/rbenv/versions/2.1.2/lib64/ruby/gems/2.1.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
        from /home/colin/dotfiles/share/rbenv/versions/2.1.2/lib64/ruby/gems/2.1.0/gems/pleaserun-0.0.7/bin/pleaserun:7:in `<top (required)>'
        from /home/colin/dotfiles/share/rbenv/versions/2.1.2/bin/pleaserun:23:in `load'
        from /home/colin/dotfiles/share/rbenv/versions/2.1.2/bin/pleaserun:23:in `<main>'
```

As of version 13.1, OpenSUSE uses systemd. Versions 12 and earlier use LSB init scripts. (13 still does, actually. Haven't fully migrated to systemd.)

Oh, and here's the ohai & facter information for my system:

ohai["platform"] #=> "opensuse"
ohai["platform_version"] #=> "13.1"
Facter["operatingsystem"].value #=> "OpenSuSE"
Facter["operatingsystemrelease"].value #=> "13.1"

Thus, I think the following additions to `PleaseRun::Detector::MAPPING` would suffice:
```ruby
["opensuse", "13"] => ["systemd", "default"]
["opensuse", "12"] => ["sysv", "lsb-3.1"]
```

**Comment by jordansissel** [comment]
@igalic 'default' is just the name of the "version" of systemd pleaserun can support.

I don't really know what backwards-incompatibility exists between systemd versions, so I didn't really know to pick any particular version to support

**Comment by evaryont** [comment]
@jordansissel IIRC, systemd has a already well-defined file format for services, and a pretty decent promise of backwards compatibility. So I'm fairly certain that the template won't be problematic in the future. (Any new features cause old versions to spit out warnings.)
