### ISSUE TITLE
Fail to run on redhat

### ISSUE THREAD

**Issue by horrorhead** [jordansissel/pleaserun#52]
Hello, and first of all nice work! I do however have an issue when trying to run pleaserun on redhat. I'm not very fluent in ruby and it seems to be ruby related. Install was pretty uneventful except for one thing:

$ sudo gem install pleaserun
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
Successfully installed cabin-0.6.1
Successfully installed clamp-0.6.3
Successfully installed atomic-1.1.16
Successfully installed hitimes-1.2.1
Successfully installed avl_tree-1.1.3
Successfully installed metriks-0.9.9.6
Successfully installed ffi-1.9.3
Successfully installed stud-0.0.17
Successfully installed mustache-0.99.5
Successfully installed insist-1.0.0
Successfully installed systemu-2.5.2
Successfully installed yajl-ruby-1.2.1
Successfully installed mixlib-cli-1.5.0
Successfully installed mixlib-config-2.1.0
Successfully installed mixlib-log-1.6.0
Successfully installed mixlib-shellout-1.4.0
Successfully installed ipaddress-0.8.0
Successfully installed ohai-6.22.0
Successfully installed pleaserun-0.0.7
19 gems installed
Installing ri documentation for cabin-0.6.1...
Installing ri documentation for clamp-0.6.3...
Installing ri documentation for atomic-1.1.16...
Installing ri documentation for hitimes-1.2.1...

unrecognized option `--markup'

For help on options, try 'rdoc --help'
$

Whe trying to run the following happends:

$ sudo pleaserun --help
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /usr/lib/ruby/gems/1.8/gems/pleaserun-0.0.7/lib/pleaserun/mustache_methods.rb:25: undefined (?...) sequence: /(?<![\\])\$/ (SyntaxError)
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/gems/1.8/gems/pleaserun-0.0.7/lib/pleaserun/platform/base.rb:3
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/gems/1.8/gems/pleaserun-0.0.7/lib/pleaserun/cli.rb:7
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
	from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/gems/1.8/gems/pleaserun-0.0.7/bin/pleaserun:5
	from /usr/bin/pleaserun:19:in `load'
	from /usr/bin/pleaserun:19

Any help appreciated!

Best regards, Mats

**Comment by jordansissel** [comment]
My general feeling is that I wish to support Ruby 1.8.7, but much of the Ruby community has long since abandoned Ruby 1.8, so there's not much I can help with here.

The only option at this time is to use a newer ruby.

If you can't upgrade, you could always use pleaserun to generate scripts on a newer system, then copy (with fpm packaging, puppet, etc) the generated scripts onto your older systems.
