### ISSUE TITLE
Cannot be embedded into recent chef due to ohai version dependency

### ISSUE THREAD

**Issue by donaldguy** [jordansissel/pleaserun#55]
As noted in #21, @paulczar has created a chef cookbook at [paulczar/chef-pleaserun](https://github.com/paulczar/chef-pleaserun)

He took the approach of loading pleaserun as a gem in the omnibus ruby install and requiring pleaserun directly in the ruby of the chef provider. In so doing, the gem is loaded in the same gem-activation context as chef itself. Thus (as reported in paulczar/chef-pleaserun#2), there results an error 
`Unable to activate pleaserun-0.0.7, because ohai-7.2.4 conflicts with ohai (~> 6.20)`

Certainly someone could just write a new cookbook that uses the `pleaserun` cli (and thus uses the `bundler exec` context), but there are things I like about Paul's approach.

For what its worth, a brief test using a modified version of pleasrun with ohai unbounded in the gemspec and thus using the latest version of ohai worked fine for my limited needs.

Is there a particular dependence on 6.20?

**Comment by rberger** [comment]
Looks like this is no longer an issue since at least pleaserun version 0.0.12 (I presume the removal of Ohai as a dependency #74 ?)

**Comment by jordansissel** [comment]
@rberger yep! I removed ohai as a dependency. <3
