### ISSUE TITLE
Does not detect Redhat 6.5

### ISSUE THREAD

**Issue by ramreddy26** [jordansissel/pleaserun#60]
Hi,

I installed on pleaserun on my redhat server and I tried to use it on kibana 4 and I am getting below error, can you let me know how to fix it?

 WARN: unable to detect ip6address
/usr/local/lib/ruby/gems/2.0.0/gems/pleaserun-0.0.7/lib/pleaserun/detector.rb:45:in `detect': PleaseRun::Detector::UnknownSystem (PleaseRun::Detector::UnknownSystem)
        from /usr/local/lib/ruby/gems/2.0.0/gems/pleaserun-0.0.7/lib/pleaserun/cli.rb:139:in `setup_defaults'
        from /usr/local/lib/ruby/gems/2.0.0/gems/pleaserun-0.0.7/lib/pleaserun/cli.rb:106:in `execute'
        from /usr/local/lib/ruby/gems/2.0.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/pleaserun-0.0.7/bin/pleaserun:7:in `<top (required)>'
        from /usr/local/bin/pleaserun:23:in `load'
        from /usr/local/bin/pleaserun:23:in `<main>'

**Comment by mflopez79** [comment]
Same on Ubuntu 14.04, with exact same error output

**Comment by ramreddy26** [comment]
Issue is fixed after Installing pleaserun 0.0.9 version and ran below step

cp pleaserun-0.0.9/templates/sysv/lsb-3.1/* pleaserun-0.0.9/templates/sysv/
