### ISSUE TITLE
Any way to incorporate this into an fpm workflow?

### ISSUE THREAD

**Issue by miked63017** [jordansissel/pleaserun#63]
For example I have a script named somescript, how would I generate startup scripts and then package it?

**Comment by jordansissel** [comment]
Related: https://github.com/jordansissel/fpm/issues/856

**Comment by jordansissel** [comment]
For today, you can look at least one example that use pleaserun+fpm together:

* https://github.com/elastic/logstash-forwarder/blob/master/Makefile#L17-L51

**Comment by miked63017** [comment]
I like the Makefile example, thanks!!!

I also like the idea in the fpm issue a lot more, should be a very useful setup. Not sure why I was thinking it would be pleaserun that would have an option to call fpm, and not vice-versa, but either way that works tying them both together would be awesome.

**Comment by jordansissel** [comment]
Closing in favor of https://github.com/jordansissel/fpm/issues/856 and the fact that there's a workaround available today https://github.com/elastic/logstash-forwarder/blob/master/Makefile#L17-L51
