### ISSUE TITLE
Proposed default behavior

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/pleaserun#64]
With no `--install` or `--json` flag, the default behavior is kind of useless. I think the default output should write to `$PWD/<platform>/<version>/...files...`

Tangential to #43

**Comment by bobprime** [comment]
I could also see wanting the default behavior be to kick out the script or scripts to standard out for further processing.  Or make install the default behavior and other options dump to $PWD or to stdout.

**Comment by jordansissel** [comment]
The `--install-prefix` flag is now available to choose where to place files and works with `--install` and without that install flag. I use this in fpm and other areas to install scripts to a staging area before installation. Seems to work ok for me:

```pleaserun -p systemd --install-prefix /tmp/example /path/too/program```
