### ISSUE TITLE
Doesn't know how to deal with Amazon AMI

### ISSUE THREAD

**Issue by edhgoose** [jordansissel/pleaserun#67]
Hi,

I'm trying to get logstash setup as a service and came across your pleaserun tool and thought I'd give it a spin. But the detector doesn't work on a blank Amazon AMI:

       pleaserun --install logstash
      /usr/local/share/ruby/gems/2.0/gems/pleaserun-0.0.9/lib/pleaserun/detector.rb:46:in `detect': amazon 2014.09 (PleaseRun::Detector::UnknownSystem)
	from /usr/local/share/ruby/gems/2.0/gems/pleaserun-0.0.9/lib/pleaserun/cli.rb:140:in `setup_defaults'
	from /usr/local/share/ruby/gems/2.0/gems/pleaserun-0.0.9/lib/pleaserun/cli.rb:107:in `execute'
	from /usr/local/share/ruby/gems/2.0/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
	from /usr/local/share/ruby/gems/2.0/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
	from /usr/local/share/ruby/gems/2.0/gems/pleaserun-0.0.9/bin/pleaserun:6:in `<top (required)>'
	from /usr/local/bin/pleaserun:23:in `load'
	from /usr/local/bin/pleaserun:23:in `<main>'

I believe it's redhat underneath...?

Ed

**Comment by bobprime** [comment]
I get the same behavior on a fresh instance.  I think the platform is upstart though this is not an area I am strong in.  /etc/init is full of .conf files that look upstart ish and there is no systemctl anywhere.

**Comment by kabo** [comment]
I think this issue should be reopened... 
```
# pleaserun --install /opt/kibana/bin/kibana
/usr/local/share/ruby/gems/2.0/gems/pleaserun-0.0.16/lib/pleaserun/detector.rb:50:in `detect': amazon 2015.03 (PleaseRun::Detector::UnknownSystem)
	from /usr/local/share/ruby/gems/2.0/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:140:in `setup_defaults'
	from /usr/local/share/ruby/gems/2.0/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:107:in `execute'
	from /usr/local/share/ruby/gems/2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/local/share/ruby/gems/2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/local/share/ruby/gems/2.0/gems/pleaserun-0.0.16/bin/pleaserun:6:in `<top (required)>'
	from /usr/local/bin/pleaserun:23:in `load'
	from /usr/local/bin/pleaserun:23:in `<main>'
```

**Comment by jordansissel** [comment]
@kabo let's discuss this new bug here: https://github.com/jordansissel/pleaserun/issues/82
