### ISSUE TITLE
Creating a pid file using upstart

### ISSUE THREAD

**Issue by edhgoose** [jordansissel/pleaserun#69]
I'm trying to ensure logstash-forwarder has a pid file, so it can be monitored by monit, a monitoring tool.

As per #67, I'm running on EC2 on an Amazon AMI and using upstart to try and run logstash-forwarder.

I've tried to hack around it to make it work, but instead ended up using the pleaserun as a template and then hacking at it until it worked. It'd be awesome if pleaserun could support this.

The issues I seemed to have were:

1. I have a chronic lack of knowledge regarding starting services :) 
2. The Upstart template doesn't create a pid 
3.  Attempts to make it produce a pid seem to be hampered by the chroot (I think? I always ended up with the wrong pid when I tried without it)

Below is what I ended up using:

    description     "Run logstash-forwarder"
    start on filesystem or runlevel [2345]
    stop on runlevel [!2345]
    
    respawn
    umask 022
    #nice
    #chroot /
    #chdir /
    #limit core <softlimit> <hardlimit>
    #limit cpu <softlimit> <hardlimit>
    #limit data <softlimit> <hardlimit>
    #limit fsize <softlimit> <hardlimit>
    #limit memlock <softlimit> <hardlimit>
    #limit msgqueue <softlimit> <hardlimit>
    #limit nice <softlimit> <hardlimit>
    #limit nofile <softlimit> <hardlimit>
    #limit nproc <softlimit> <hardlimit>     
    #limit rss <softlimit> <hardlimit>
    #limit rtprio <softlimit> <hardlimit>
    #limit sigpending <softlimit> <hardlimit>
    #limit stack <softlimit> <hardlimit>
    
    pre-start script
      if [ "$status" -gt 0 ] ; then
        echo "Prestart command failed with code $status."
    
        # Per init(5) docs, simply calling 'stop' will abort this start.
        stop
      fi
    end script
    
    post-start script
      PID=`status logstash-forwarder | egrep -oi '([0-9]+)$' | head -n1`
      echo $PID > /var/run/logstash-forwarder.pid
    end script
    
    post-stop script
        rm -f /var/run/logstash-forwarder.pid
    end script
    
    exec chroot --userspec root:root / /usr/local/logstash-forwarder/logstash-forwarder -config=/usr/local/etc/logstash-forwarder/    config/    

Thanks!

**Comment by igalic** [comment]
upstart doesn't really need/use a pid-file.
it tracks the "daemon" (it prefers you start the daemon in forderground, and don't actually make it daemonize)  by itself (using… ptrace…):

**Comment by edhgoose** [comment]
It's not upstart that I'd like the pid for. It's monit, which uses a pid to determine if it's running. I'm not sure of a way to make monit monitor without it, so this seemed an effective solution.

**Comment by jordansissel** [comment]
Why not use the status call of upstart or Sysv to ask if it's working?

**Comment by edhgoose** [comment]
My understanding, until just 30 seconds ago, was that monit can only monitor a process using a pid file, hence the request.

Looking through the monit documentation, there may be a regex monitor too which may enable me to do that. Let me check first thing tomorrow and report back.

**Comment by edhgoose** [comment]
Well, that's infuriating simple. In monit "check process logstash-forwarder matching "logstash-forwader"" works absolutely fine.

Pid no longer required. Apologies for wasting your time!

**Comment by jordansissel** [comment]
@edhgoose I am glad you got it working :)
