### ISSUE TITLE
Remove dependency on Ohai

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/pleaserun#74]
Platform detection is nice, but Ohai requires Ruby C extensions which don't work under JRuby.

**Comment by jordansissel** [comment]
Done in 7f53321 - ohai is now optional.

**Comment by igalic** [comment]
what about facter?

**Comment by jordansissel** [comment]
@igalic I haven't tested yet. Could you see if there's any C-extension dependencies of facter?

**Comment by igalic** [comment]
created a gemfile:
```Gemfile
source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem 'facter', ">= 1.0.0"
```
and ran `bundle`, this is the resulting `Gemfile.lock`
```Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.2.8)
    facter (2.4.1)
      CFPropertyList (~> 2.2.6)

PLATFORMS
  ruby

DEPENDENCIES
  facter (>= 1.0.0)
```
on debuntu, facter depends on stuff like
```
Depends: ruby | ruby-interpreter, virt-what, pciutils
```
to be able to do deeper introspection of the hardware (and tell if its running in a virtual machine, etc..)

**Comment by jordansissel** [comment]
@igalic I'm open to adding facter, though the nice puppet folks are working on implementing parts of facter in C, which makes that pure-rubyness go away a bit. Ahh well... Possible we can improve and implement just OS detection parts in pleaserun w/ the old parts of facter?

**Comment by jordansissel** [comment]
7f53321f removed ohai as a required dependency.
