### ISSUE TITLE
Service Stop and Userdel 

### ISSUE THREAD

**Issue by packplusplus** [jordansissel/pleaserun#81]
userdel can fail if there are processes running with that UID (user still logged in). There is a flag, -f, that will tell userdel to run regardless. Or you could a service stop (what pre-uninstall in httpd does) 

<pre> preuninstall scriptlet (using /bin/sh):
if [ $1 = 0 ]; then
        /sbin/service httpd stop > /dev/null 2>&1
        /sbin/chkconfig --del httpd
        /sbin/service htcacheclean stop > /dev/null 2>&1
        /sbin/chkconfig --del htcacheclean
fi</pre>

Some init scripts (like for logstash) they give up after N tries to stop the daemon, which may make it fail in some cases. However, the man page for userdel -f has a warning about leaving a system in an inconsistent state. 

@jordansissel also offered up being open to "pkill -9 -u <USER>"

Discussion started here: https://github.com/elastic/kibana/pull/3212

**Comment by jordansissel** [comment]
+1, though I still need to do a bit more research so this is implemented in a safe-enough way (meaning: correctly for rpm, deb, etc systems).

**Comment by packplusplus** [comment]
Closing, I lost context of if this is still an issue and don't want to clutter up the issues history.
