### ISSUE TITLE
Support detection of amazon 2015.03

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/pleaserun#82]

**Comment by jordansissel** [comment]
@kabo What distro is Amazon 2015.03 based on?

**Comment by kabo** [comment]
AWS Linux is loosely based on RHEL. But you have a few more versions than that to add...
* [2011.09](http://aws.amazon.com/amazon-linux-ami/2011.09-release-notes/)
* [2012.03](http://aws.amazon.com/amazon-linux-ami/2012.03-release-notes/)
* [2012.09](http://aws.amazon.com/amazon-linux-ami/2012.09-release-notes/)
* [2013.03](http://aws.amazon.com/amazon-linux-ami/2013.03-release-notes/)
* [2013.09](http://aws.amazon.com/amazon-linux-ami/2013.09-release-notes/)
* [2014.03](http://aws.amazon.com/amazon-linux-ami/2014.03-release-notes/)
* [2014.09](http://aws.amazon.com/amazon-linux-ami/2014.09-release-notes/)
* [2015.03](http://aws.amazon.com/amazon-linux-ami/2015.03-release-notes/)

**Comment by jordansissel** [comment]
Which versions of RHEL for each version of AWS Linux?

**Comment by jordansissel** [comment]
Once I have the RHEL<->AWSLinux version mapping, I can totally update the detector to use the right init systems.

**Comment by kabo** [comment]
AWS is pretty bad at documenting this stuff unfortunately. I know I got 2015.03 to work with upstart 0.6.5.

**Comment by kabo** [comment]
They may be following Fedora closer than RHEL according [this thread on superuser.com](http://superuser.com/questions/302813/amazon-linux-ami-release-2010-11-1-corresponds-to-which-rhel-version-4-5-6).

**Comment by jordansissel** [comment]
This should be fixed now because the platform detection mechanism no longer needs to find out what the vendor and operating system is. Instead, it checks properties of the local system for signs that a given service platform is in place.

Let me know if this is still broken, though, since I don't test on Amazon Linux.
