### ISSUE TITLE
error: "Could not find template file for 'init.sh'" when using -p

### ISSUE THREAD

**Issue by FlorinAndrei** [jordansissel/pleaserun#87]
Ubuntu 14.04, more or less up to date. Installed pleaserun recently.

If I run it without -p, it's fine:

```
$ pleaserun --no-install-actions --chdir /opt/statsd --name statsd --description "Simple daemon for easy stats aggregation" "node stats,js config.js"
No platform selected. Autodetecting... {:platform=>"upstart", :version=>"1.5", :level=>:warn}
Writing file {:destination=>"/tmp/studtmp-67e4538324834a458cac931e75c7a167a1c7629c3f53ed5f8b55b0723524/etc/init/statsd.conf"}
```

But if I provide -p, it errors out:

```
$ pleaserun -p sysv -v 4.1 --no-install-actions --chdir /opt/statsd --name statsd --description "Simple daemon for easy stats aggregation" "node stats,js config.js"
/var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/platform/base.rb:168:in `render_template': Could not find template file for 'init.sh'. Tried all of these: ["/var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/platform/../../../templates/sysv/4.1/init.sh", "/var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/platform/../../../templates/sysv/default/init.sh", "/var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/platform/../../../templates/sysv/init.sh"] (PleaseRun::Platform::Base::InvalidTemplate)
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/platform/sysv.rb:10:in `block in files'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/installer.rb:18:in `each'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/installer.rb:18:in `install_files'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:177:in `run_human'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.16/lib/pleaserun/cli.rb:128:in `execute'
	from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /var/lib/gems/1.9.1/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /var/lib/gems/1.9.1/gems/pleaserun-0.0.16/bin/pleaserun:6:in `<top (required)>'
	from /usr/local/bin/pleaserun:23:in `load'
	from /usr/local/bin/pleaserun:23:in `<main>'
```

Any idea what's going on?

**Comment by jordansissel** [comment]
Pleaserun is looking for sysv platform version 4.1. Only one implementation (version) of sysv currently exists in pleaserun, and that is [lsb-3.1](https://github.com/jordansissel/pleaserun/tree/master/templates/sysv).

If you use `-p sysv -v lsb-3.1` it should be ok.

Technical details aside, I recommend Upstart highly over sysv, but the choice is always yours, I still support sysv via pleaserun.

If lsb-4.1 differs significantly from lsb-3.1, we can add support for lsb-4.1.

Let me know what you want :)

**Comment by FlorinAndrei** [comment]
I think my example was not perfect - it errors out even without -v, it's enough to just add -p.

Anyway, forcing -v lsb-3.1 made the error disappear. Thank you for answering so quickly.

The resulting init script had some issues, but it's hard to tell whether those were due to pleaserun, or to the characteristics of my environment here. I've fixed it by hand and now everything works.

**Comment by jordansissel** [comment]
I think this has been fixed. Please let me know if otherwise.

**Comment by jordansissel** [comment]
(btw, lsb4.1 is not supported, so trying to do '-v 4.1' won't likely result in what you want; not until someone adds support for it)
