### ISSUE TITLE
neither ohai nor facter libraries are found

### ISSUE THREAD

**Issue by FunTimeCoding** [jordansissel/pleaserun#95]
I installed pleaserun like that:

```
gem install pleaserun
```

But when I run it to do this:

```
pleaserun --install /home/shiin/services/bin/anoperc
```

I get this error:

```
/usr/local/opt/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pleaserun-0.0.16/lib/pleaserun/detector.rb:45:in `rescue in rescue in detect': Could not detect because neither ohai nor facter libraries are found (PleaseRun::Detector::UnknownSystem)
```

These are my installed gems.

```
bigdecimal (1.2.7, 1.2.6)
cabin (0.7.2)
clamp (1.0.0)
insist (1.0.0)
io-console (0.4.3)
json (1.8.3, 1.8.1)
minitest (5.8.3, 5.4.3)
mustache (1.0.2, 0.99.8)
pleaserun (0.0.16)
power_assert (0.2.6, 0.2.2)
psych (2.0.15, 2.0.8)
rake (10.4.2)
rdoc (4.2.0)
stud (0.0.22)
test-unit (3.1.5, 3.0.8)
```

I suspect it didn't install the dependency.

**Comment by jordansissel** [comment]
ohai and facter are optional dependencies only used to automatically detect the target operating system. You can install them with `gem install facter` or `gem install ohai` (you only need one of them) if you wish.

Alternately, you can specify the target yourself with the `-p` (platform) and `-v` (platform version) flags. For example, `-p sysv -v lsb-3.1` will target sysv-style init for lsb-3.1 version. There are many platforms available (systemd, upstart, launchd, etc).

**Comment by jordansissel** [comment]
I confess the error message you get needs some improvement.

**Comment by FunTimeCoding** [comment]
I see. Thank you.

**Comment by untergeek** [comment]
This is moot now that neither `ohai` nor `facter` are required...

**Comment by jordansissel** [comment]
Indeed! The platform detector has been rewritten to not use facter or ohai. <3

**Comment by jordansissel** [comment]
(This problem should be fixed)
