### ISSUE TITLE
support redhat's pidfile: comment block for sysv script compatibility with systemd

### ISSUE THREAD

**Issue by wbean1** [jordansissel/pleaserun#96]
This is an absurd request, and I won't go too deep into why I'm trying to get this to work, but in RedHat 7 (using systemd) you can still place a sysv init script and magic happens to convert it into a systemd unit file.  However, the two systems can easily become out of sync on the 'status' of the service if an administrator were to stop the service with a sysv-esq command:

```
# /etc/init.d/myservice status
myservice is not running

# systemctl is-active myservice
active
```

From http://www.freedesktop.org/wiki/Software/systemd/Incompatibilities/:
````
If systemd doesn't know which PID is the main PID of a service, it will not be able to track its
runtime, and hence a service exiting on its own will not make systemd consider it stopped. 
Use the Red Hat "pidfile: " syntax in the SysV script header comment block to let systemd 
know which PID file (and hence PID) belongs to your service. Note that systemd cannot know
if a SysV service is one of the kind where the runtime is defined by a specific process or
whether it is one where there is none, hence the requirement of explicit configuration of a PID
file in order to make systemd track the process lifetime.
````

From https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Unit_Files.html:
```
Finding Files Used by the Service
...
The PID file specified on the #pidfile init script line is imported to the unit file
with the PIDFile option.
```
I can just keep manually tossing in the `# pidfile: ` line if this is all too far-fetched.  I get that I'm swimming against the current here...

**Comment by wbean1** [comment]
closing this. I now understand how dumb it is to use pidfiles with systemd in the first place.  sorry for the added noise in inithell.

**Comment by jordansissel** [comment]
I'm glad you got things figured out! And it wasn't dumb to think about
using pidfiles with systemd, even if it's not necessarily useful, it's good
to think about how to query processes and such. You're on the right track
:heart:
